default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: <%= ENV['DB_HOST'] %>
development:
  <<: *default
  database: elearnig_sys_development
test:
  <<: *default
  database: elearning_sys_test
  production:
   adapter: postgresql
   datebase: e-learning-sys
   pool: 5
   timeout: 5000
   
